AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Profile Manager - Static Website Distribution Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: aws-profile-manager
    Description: Project name used for resource naming

  WebsiteBucketName:
    Type: String
    Description: S3 bucket name for hosting the static website (from secrets)

  BinariesBucketName:
    Type: String
    Description: S3 bucket name for hosting application binaries (from secrets)

  DomainName:
    Type: String
    Description: Custom domain name for CloudFront distribution (e.g., downloads.example.com)

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for DNS records

  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for HTTPS (must be in us-east-1 region for CloudFront)

Resources:
  # ================================
  # S3 BUCKETS CONFIGURATION
  # ================================

  # S3 Bucket for Website Content
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3600
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Static Website

  # Bucket Policy for Website Bucket - Public Read Access
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'

  # S3 Bucket for Application Binaries
  BinariesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BinariesBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            MaxAge: 3600
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: Application Binaries

  # Bucket Policy for Binaries Bucket - Public Read Access
  BinariesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BinariesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${BinariesBucket.Arn}/*'

  # ================================
  # CLOUDFRONT DISTRIBUTION
  # ================================

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub '${ProjectName} - Downloads Distribution'
        Enabled: true
        HttpVersion: http2and3
        PriceClass: PriceClass_100 # North America and Europe only (cost-effective)
        IPV6Enabled: true

        # Custom domain
        Aliases:
          - !Ref DomainName

        # SSL/TLS Certificate
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        # Origins
        Origins:
          # Website Origin (React Vite build)
          - Id: WebsiteOrigin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''

          # Binaries Origin (installers)
          - Id: BinariesOrigin
            DomainName: !GetAtt BinariesBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''

        # Default Cache Behavior (Website) - respect origin Cache-Control (long for assets, short for HTML)
        DefaultCacheBehavior:
          TargetOriginId: WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized (respects origin headers)
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin

        # Cache Behaviors
        CacheBehaviors:
          # Downloads path behavior
          - PathPattern: '/downloads/*'
            TargetOriginId: BinariesOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin

        # Custom Error Responses (SPA routing support)
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300

      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ================================
  # ROUTE 53 CONFIGURATION
  # ================================

  # Route 53 A Record - Points custom domain to CloudFront
  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID (global constant)
        EvaluateTargetHealth: false

Outputs:
  WebsiteBucketName:
    Description: Name of the S3 bucket hosting the website
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucket'

  BinariesBucketName:
    Description: Name of the S3 bucket hosting the binaries
    Value: !Ref BinariesBucket
    Export:
      Name: !Sub '${AWS::StackName}-BinariesBucket'

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'

  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDomain'

  WebsiteURL:
    Description: Website URL (Custom Domain)
    Value: !Sub 'https://${DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  DownloadsURL:
    Description: Downloads URL
    Value: !Sub 'https://${DomainName}/downloads/'
    Export:
      Name: !Sub '${AWS::StackName}-DownloadsURL'

  WebsiteBucketArn:
    Description: ARN of the website bucket
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucketArn'

  BinariesBucketArn:
    Description: ARN of the binaries bucket
    Value: !GetAtt BinariesBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BinariesBucketArn'
